workspace:
  base: /test
  path: platform
matrix:
  FPFIS_PHP_VERSION:
    - 56
  PLATFORM_PROFILE:
    - standard
  BEHAT_BROWSER:
    - chrome
    - firefox

services:
  # centos 6 + httpd + php${FPFIS_PHP_VERSION}
  web:
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    environment:
      - DOCUMENT_ROOT=/test/platform/build
  # centos 6 + mysql community
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes}
  selenium:
    image: selenium/standalone-${BEHAT_BROWSER}:2.53.0
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
  tunnel:
    image: fpfis/drone-frpc-plugin:latest
    when:
      event: [ push, pull_request, tag ]
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=platform-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/toolkit/.frpc

# Start a pipeline ( sets of steps )
# Be advised that the container will be a new one every step
# therefore loosing all customization made in the previous step
# ( php settings, extension install )
pipeline:

  # Step name "prepare"
  prepare-php:
    # Use php${FPFIS_PHP_VERSION} image
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    # Run the following commands
    commands:
      - cat /proc/{cpu,mem}info|sort|uniq -c|egrep -i "name|memtotal"
      - php --version
      - composer global require hirak/prestissimo
      - composer install --ansi

  prepare-database:
    # Use php${FPFIS_PHP_VERSION} image
    image: fpfis/mysql56
    # Run the following commands
    commands:
      - mysqladmin -h mysql create platform

  # Prepare dev for selenium
  build-dev-selenium:
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    commands: 
      - composer global require hirak/prestissimo
      - ./bin/phing build-platform-dev -Dcomposer.bin=$(which composer) -Dbehat.base_url='http://web:8080' -Dbehat.wd_host.url='http://selenium:4444/wd/hub' -Dbehat.browser.name=${BEHAT_BROWSER} -Dvarnish.server.port=6080 -Dplatform.profile.name=multisite_drupal_${PLATFORM_PROFILE}

  # Check code standards :
  qa:
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    commands: 
      - ./bin/phpcs

  # And so on ...
  install:
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    commands:
      - ./bin/phing install-platform -Dcomposer.bin=$(which composer) -Ddrupal.db.host=mysql -Ddrupal.db.user=root -Ddrupal.db.password="" -Ddrupal.db.name=platform -Dplatform.profile.name=multisite_drupal_${PLATFORM_PROFILE}
      - chown -R 1000:1000 build/sites/default
      - chmod -R 777 /tmp 
      
  unit-test:
    group: test
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    commands:
      - ./bin/phpunit -c tests/phpunit.xml

  behat-test:
    group: test
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    commands:
      - ./bin/behat -v -c build/behat.yml  --colors -f pretty --strict

  package:
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    when:
      environment:
        PLATFORM_PROFILE: standard
      event: tag
    commands:
      - ./bin/phing build-multisite-dist -Dcomposer.bin=$(which composer)
      - tar cz --strip-components=1 build > ../platform-dev-${DRONE_TAG}.tar.gz
